name: Build Docker Image

on:
  workflow_dispatch:
    inputs:
      gitTag:
        description: "Git tag of the bsc repository"
        required: true
      imageTag:
        description: "Tag to be used for the built image"
        required: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_REPOSITORY: xjonathanlei/bsc

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Clone BSC Repository
        run: |
          git clone --recursive -b "${{ github.event.inputs.gitTag }}" --depth 1 https://github.com/binance-chain/bsc.git

      - name: Build Docker Image
        run: |
          cd bsc
          docker build -t ${DOCKER_REPOSITORY}:${{ github.event.inputs.imageTag }} -f ./Dockerfile .

      - name: Push Docker Image
        run: |
          docker push ${DOCKER_REPOSITORY}:${{ github.event.inputs.imageTag }}
